import {
    GiHand,
    GiSoccerBall,
    GiGrass,
    GiPlainSquare,
    GiOakLeaf,
    GiSuperMushroom,
    GiLips,
    GiCharm,
    GiNightSleep,
    GiWoodStick,
    GiRetroController,
    GiPaperPlane,
  } from "react-icons/gi";
const allItems = {
    lettuce: {
      value: 3,
      icon: <GiGrass className="healthColor" />,
      type: "health",
      name: "lettuce",
      phrase: "Feed with lettuce",
    },
    tofu: {
      value: 10,
      icon: <GiPlainSquare className="healthColor" />,
      type: "health",
      name: "tofu",
      phrase: "Feed with tofu",
    },
    kale: {
      value: 15,
      icon: <GiOakLeaf className="healthColor" />,
      type: "health",
      name: "kale",
      phrase: "Feed with kale",
    },
    superfood: {
      value: 30,
      icon: <GiSuperMushroom className="healthColor" />,
      type: "health",
      name: "superfood",
      phrase: "Feed with superfood!",
    },
    coo: {
      value: 3,
      icon: <GiLips className="loveColor" />,
      type: "love",
      name: "coo",
      phrase: "Coo at Mata",
    },
    pet: {
      value: 10,
      icon: <GiHand className="loveColor" />,
      type: "love",
      name: "pet",
      phrase: "Pet Mata",
    },
    cuddle: {
      value: 15,
      icon: <GiNightSleep className="loveColor" />,
      type: "love",
      name: "cuddle",
      phrase: "Cuddle on Mata",
    },
    heart: {
      value: 30,
      icon: <GiCharm className="loveColor" />,
      type: "love",
      name: "heart",
      phrase: "<3 <3 <3",
    },
    stick: {
      value: 3,
      icon: <GiWoodStick className="playColor" />,
      type: "play",
      name: "stick",
      phrase: "Play with a stick",
    },
    ball: {
      value: 10,
      icon: <GiSoccerBall className="playColor" />,
      type: "play",
      name: "ball",
      phrase: "Play with a ball",
    },
    videogame: {
      value: 15,
      icon: <GiRetroController className="playColor" />,
      type: "play",
      name: "videogame",
      phrase: "Play with a video game",
    },
    travel: {
      value: 30,
      icon: <GiPaperPlane className="playColor" />,
      type: "play",
      name: "travel",
      phrase: "Travel!",
    },
  };

  export default allItems;